### ISSUE TITLE
EC-CUBE3.0.8で試したときに、カテゴリコンテンツの登録が表示されない

### ISSUE THREAD

**Issue by ghost** [EC-CUBE/category-content-plugin#5]
http://www.ec-cube.net/products/detail.php?product_id=1070
のページの画面キャプチャが見づらく、いまいち把握しきれていないのですが、カテゴリコンテンツの登録は、商品管理 ＞ カテゴリ登録の画面で行えるということで間違いないでしょうか？

EC-CUBE3.0.8に入れて、プラグインを有効にしてみたのですが、カテゴリコンテンツを登録するところが見当たりません。
他のプラグインを無効にしても、表示されないように思います。

何が原因なのでしょうか？

**Comment by ghost** [comment]
登録はプラグインを入れ直したところ表示されましたが、imgタグやdivタグを入れると、

PHP Warning:  DOMNode::insertBefore(): Document Fragment is empty ~ eccube3/app/Plugin/CategoryContent/CategoryContentEvent.php on line 69

と、変数（$node）が空っぽになってしまうようです。
ちなみにpタグだけとかだと表示されます。タグで何か制御を行っているのでしょうか？

**Comment by ryo-endo** [comment]
HTMLタグが含まれていた場合に、
特殊文字（ダブルクォーテーションなど）をエスケープできていませんでした。
v0.0.3で修正します。
